#spring.application.name=reactive-kafka-sandbox

spring:
  #application:
  #  name: reactive-kafka-sandbox

  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: demo-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        "group.instance.id": "1"
        "spring.json.value.default.type": "jayslabs.kafka.section10.springkafka.ConsumerOrderDTO"
        "spring.json.trusted.packages": "jayslabs.kafka.section10.springkafka"
        "spring.deserializer.value.delegate.class": "org.springframework.kafka.support.serializer.JsonDeserializer"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer